application: bashlive webpipes
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /debug
  script: server.php 
- url: /json_print_r
  script: json_print_r/index.php 
- url: /.*
  script: index.php 
