application: neon-semiotics-490
version: v1_0_1_baconsandwhich
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /debug
  script: server.php 
- url: /json_print_r
  script: json_print_r/index.php 
- url: /csv2json 
  script: csv2json/index.php 
- url: /xml2json 
  script: xml2json/index.php 
- url: /json2csv 
  script: json2csv/index.php 
- url: /jsonpath 
  script: jsonpath/index.php 
- url: /xpath 
  script: xpath/index.php 
- url: /markdown 
  script: markdown/index.php 
- url: /url2html 
  script: url2html/index.php 
- url: /striphtml 
  script: striphtml/index.php 
- url: /.*
  script: index.php 
